apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-app.fullname" . }}-secret
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
type: Opaque # Tipo genérico para datos arbitrarios. Otros tipos incluyen kubernetes.io/tls, service-account-token.
data:
  dbUsername: {{ "myusername" | b64enc | quote }}
  dbPassword: {{ "mypassword" | b64enc | quote }}
